# BEGIN BOOKTRAIL MANAGED RULES
destination booktrail_reader_metrics {
    file("/mnt/us/extensions/booktrail/log/metrics_reader_$YEAR$MONTH"
         template("$MSG\n"));
};
filter booktrail_reader_filter {
    facility(local7) and match("reader\\.activeDuration") and not match("===");
};
log {
    source(src);
    filter(booktrail_reader_filter);
    destination(booktrail_reader_metrics);
};
# END BOOKTRAIL MANAGED RULES
